simulation_horizon: 24 # hours
prediction_horizon: 3 # hours
robust_horizon: 2 # steps
branch_factor: 2

actions_per_hour: 6
logpath: "./logs/"
datafile: "./data/load_PV3.csv"
loads_trainfile: "./data/loads_train.csv"
openloop: False
perfect_predictions: False

battery:
  x_initial: 0.35
  C_MAX: 1000
  nb: 0.913724

system:
  C_MAX: 1000
  nb_c: 0.913724
  nb_d: 0.913724
  x_min: 0.3
  x_max: 0.9
  x_ref: 0.7
  Pb_max: 1000
  Pg_max: 1000
  battery_cost: 0.128
  grid_cost: 10
  ref_cost: 10
  verbose: False
