simulation_horizon: 40 # hours
prediction_horizon: 10 # hours
robust_horizon: 1 # steps
branch_factor: 1

actions_per_hour: 6
logpath: "./logs/"
testfile: "./data/8.4_cleaned.csv"
trainfile: "./data/8.4_train.csv"
solcast_file: "./data/solcast_cleaned.csv"
price_file: "./data/spot_prices.csv"
openloop: False
perfect_predictions: False

battery:
  x_initial: 0.6
  C_MAX: 1000
  nb: 0.913724

system:
  C_MAX: 1000
  nb_c: 0.913724
  nb_d: 0.87
  x_min: 0.2
  x_max: 0.8
  x_ref: 0.6
  Pb_max: 1000
  Pg_max: 1000
  battery_cost: -10
  grid_cost: 10
  ref_cost: 1
  verbose: False
