simulation_horizon: 24 # hours
prediction_horizon: 3 # hours
robust_horizon: 2 # steps
branch_factor: 3

actions_per_hour: 6
logpath: "./logs/"
datafile: "./data/09.03_cleaned.csv"
loads_trainfile: "./data/09.03_cleaned.csv"
solcast_file: "./data/solcast_cleaned.csv"
openloop: False
perfect_predictions: True

battery:
  x_initial: 0.88
  C_MAX: 1000
  nb: 0.913724

system:
  C_MAX: 1000
  nb_c: 0.913724
  nb_d: 0.87
  x_min: 0.3
  x_max: 0.9
  x_ref: 0.7
  Pb_max: 1000
  Pg_max: 1000
  battery_cost: 0.128
  grid_cost: 2
  ref_cost: 100
  verbose: False
