simulation_horizon: 24 # hours
prediction_horizon: 6 # hours
N_scenarios: 1
perfect_predictions: False

plot: True
foldername: 

start_year: 2021
start_month: 4
start_day: 7
actions_per_hour: 6
logpath: "./logs/"
testfile: "./data/10.5_alldata.csv"
trainfile: "./data/10.5_train.csv"
solcast_file: "./data/solcast_forecasts.csv"
price_file: "./data/spot_prices.csv"

battery:
  x_initial: 0.7
  C_MAX: 1000
  nb_c: 0.91
  nb_d: 0.91

system:
  x_min: 0.2
  x_max: 0.8
  x_ref: 0.6
  Pb_max: 1000
  Pg_max: 1000
  battery_cost: 0.01
  peak_cost: 52
  old_grid_fee: 0
  terminal_cost: -812
  verbose: False
