days: 1
action_per_hour: 6
x_inital: 0.4
x_noise: 0
logpath: "./logs/"
datafile: "./data/load_PV3.csv"
log: True
grid_buy: 1.5
grid_sell: 1.5

pv-cell:
    max_power: 80
    add_noise: False

p-load:
    max_power: 80
    add_noise: False

system:
    C_MAX: 700
    nb_c: 0.8
    nb_d: 0.8
    x_min: 0.3
    x_max: 0.9
    x_ref: 0.7
    Pb_max: 1000
    Pg_max: 500
    battery_cost: 0.1
    ref_cost: 10
    verbose: False