simulation_horizon: 24 # hours
prediction_horizon: 6 # hours
actions_per_hour: 6
logpath: "./logs/"
datafile: "./data/load_PV3.csv"
loads_trainfile: "./data/loads_train.csv"
predictions: data #  perfect, data, constant, arima, scaled_mean, best
plot_predictions: False

components:
  B1:
    x_inital: 0.7
    nb: 0.913
    C_MAX: 300
  B2:
    x_inital: 0.7
    nb: 0.913
    C_MAX: 300
  B3:
    x_inital: 0.7
    nb: 0.913
    C_MAX: 300
