simulation_horizon: 1
prediction_horizon: 2
actions_per_hour: 6
x_inital: 0.4
logpath: "./logs/"
datafile: "./data/load_PV3.csv"
perfect_predictions: True
plot_predictions: False

simulations:
    pv_power: 80
    pv_noise: False
    pl_power: 80
    pl_noise: False
    grid_buy: 1.5
    grid_sell: 1.5

system:
    C_MAX: 700
    nb_c: 0.8
    nb_d: 0.8
    x_min: 0.3
    x_max: 0.9
    x_ref: 0.7
    Pb_max: 1000
    Pg_max: 33
    battery_cost: 0.1
    ref_cost: 100
    grid_cost: 10
    verbose: False