simulation_horizon: 30  # hours
prediction_horizon: 10 # hours
robust_horizon: 1 # steps
branch_factor: 3

actions_per_hour: 6
logpath: "./logs/"
testfile: "./data/23.4_cleaned.csv"
trainfile: "./data/23.4_train.csv"
solcast_file: "./data/solcast_cleaned.csv"
price_file: "./data/spot_prices.csv"
openloop: False
perfect_predictions: False 

battery:
  x_initial: 0.3
  C_MAX: 1000
  nb_c: 0.913724
  nb_d: 0.95


system:
  C_MAX: 1000
  nb_c: 0.913724
  nb_d: 0.95
  x_min: 0.2
  x_max: 0.8
  x_ref: 0.6
  Pb_max: 1000
  Pg_max: 1000
  battery_cost: 0.01
  grid_cost: 0.01
  ref_cost: 1
  verbose: False
