simulation_horizon: 24    # hours
prediction_horizon: 2   # hours
actions_per_hour: 6
x_inital: 0.9
logpath: "./logs/"
datafile: "./data/cloudy.csv"
perfect_predictions: True
plot_predictions: True

simulations:
    pv_power: 80
    pv_noise: False
    pl_power: 80
    pl_noise: False
    grid_buy: 1.5
    grid_sell: 1.5

system:
    C_MAX: 700
    nb_c: 0.8
    nb_d: 0.8
    x_min: 0.3
    x_max: 0.9
    x_ref: 0.7
    Pb_max: 1000
    Pg_max: 500
    battery_cost: 0.01
    ref_cost: 0.2
    grid_cost: 1000
    verbose: False